text_color: ''
author: ''
favicon: ''
site_logo: ''
description: The last theme you'll ever need. Maybe.
background_color_class: bg-green
recent_posts_number: 5
ananke_socials:
  - name: github
    url: 'https://github.com/eamadio/'
  - name: linkedin
    url: 'https://www.linkedin.com/in/emmanuelamadio/'
